### PR TITLE
indices to index

### PR DESCRIPTION
**Pull request by gr2m**
currently only adds a failing test. Not sure how to fix it, as it conflicts with "invoices to invoice".

### CODE REVIEW

**Comment by onbjerg** [comment]
Use `inflectors.addRule('index', 'indices')` in your code. Maybe the module should ship with some defaults? @nicklasmoeller 🤔

**Comment by mex** [comment]
Both indexes and indices are per thefreedictionary.com valid plural forms of index, so I think it would be presumptuous to add a default rule.

**Comment by gr2m** [comment]
works for me, feel free to close the issue :)

**Comment by onbjerg** [comment]
@mex I think it would also be presumptuous to not add the rule. This presumes people use "indexes" as the plural form. 🕵

**Comment by mex** [comment]
Haha, true!
Without any statistical backing, I'm thinking that there are more words ending in x, that are suffixed with -es in its plural form, but as said I have nothing to base this on.

**Comment by nicklasmoeller** [comment]
Pretty sure RoR has the most mature inflectors library in the wild. 

Would be neat with compliance for what RoR provides. 
https://github.com/rails/rails/blob/7f18ea14c893cb5c9f04d4fda9661126758332b5/activesupport/lib/active_support/inflections.rb

**Comment by onbjerg** [comment]
There's already a package on npm that implements RoR inflectors AFAIK. I think it's called inflect.

**Pull request closed without merging**
